title: Wallet Identity Card API
description: Generate visual identity cards for Stacks wallets
theme: just-the-docs

url: https://whoabuddy.github.io
baseurl: /wallet-id-card

# Repository
aux_links:
  "View on GitHub": https://github.com/whoabuddy/wallet-id-card

# Footer
footer_content: "Powered by <a href=\"https://stx402.com\">stx402</a> and <a href=\"https://hiro.so\">Hiro</a>"

# Color scheme
color_scheme: dark

# Enable copy code button
enable_copy_code_button: true

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Callouts
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
